version: '3'
services:
  weechat:
    image: jkaberg/weechat
    entrypoint: /bin/sh
    command:
      - -c
      - |
       apk add --no-cache py2-pip
       pip install websocket-client
       /run.sh
    stdin_open: true
    tty: true
    logging:
      driver: none
    environment:
      WEECHAT_HOME: /weechat
    volumes:
      - /mnt/disks/gce-containers-mounts/gce-persistent-disks/weechat:/weechat
  caddy:
    build:
      context: ./caddy
    environment:
      - RELAY_FQDN
      - ACME_EMAIL
      - ACME_AGREE
      - NAMECHEAP_API_USER
      - NAMECHEAP_API_KEY

    depends_on:
      - weechat
    ports:
      - 9001:9001
