version: '3'
services:
  weechat:
    image: jkaberg/weechat
    stdin_open: true
    tty: true
    logging:
      driver: none
    volumes:
      - type: bind
        source: /mnt/disks/gce-containers-mounts/gce-persistent-disks/weechat
        target: /weechat
  caddy:
    build:
      context: ./caddy
    environment:
      - RELAY_FQDN
      - ACME_EMAIL
      - ACME_AGREE
      - NAMECHEAP_API_USER
      - NAMECHEAP_API_KEY

    depends_on:
      - weechat
    ports:
      - 9001:9001
